pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-cache
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Cache
  desc: Simple cache method for the build workspace
  type: cache
  image: plugins/drone-cache
  labels:
    - cache
